/* Generated by Yosys 0.53+70 (git sha1 3ef4c91c3, clang++ 18.1.8 -fPIC -O3) */

module mux(a, b, sel, y);
  input a;
  wire a;
  input b;
  wire b;
  input sel;
  wire sel;
  output y;
  wire y;
  sg13g2_mux2_1 _0_ (
    .A0(a),
    .A1(b),
    .S(sel),
    .X(y)
  );
endmodule
